// Generated by Skill uni-mp-analy 2.0.0.
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_PATH = fileURLToPath(import.meta.url);
const TEMPLATE_PATH = fileURLToPath(new URL('../assets/report-template.html', import.meta.url));
const DATA_PLACEHOLDER = '__REPORT_DATA__';

/**
 * 生成可通过 file:// 直接打开的单文件 HTML 报告。
 *
 * @param {object} analysis 符合 schemaVersion 1 的分析结果；未知字段会原样保留。
 * @param {string} outputPath 输出 HTML 路径；为保护既有文件，只允许创建新文件。
 * @returns {Promise<string>} 已写入的绝对输出路径。
 */
export async function generateReport(analysis, outputPath) {
  if (!outputPath || typeof outputPath !== 'string') {
    throw new TypeError('outputPath 必须是非空字符串');
  }

  const template = await readFile(TEMPLATE_PATH, 'utf8');
  const placeholderCount = template.split(DATA_PLACEHOLDER).length - 1;
  if (placeholderCount !== 1) {
    throw new Error(`报告模板必须且只能包含一个 ${DATA_PLACEHOLDER} 占位符`);
  }

  const normalizedAnalysis = analysis && typeof analysis === 'object' ? analysis : {};
  const serialized = escapeJsonForHtml(JSON.stringify(normalizedAnalysis));
  const html = template.replace(DATA_PLACEHOLDER, () => serialized);
  const absoluteOutputPath = resolve(outputPath);

  await mkdir(dirname(absoluteOutputPath), { recursive: true });
  await writeFile(absoluteOutputPath, html, { encoding: 'utf8', flag: 'wx' });
  return absoluteOutputPath;
}

/**
 * 避免 JSON 在 script 元素中提前闭合或被解释为 HTML，并兼容 U+2028/U+2029。
 *
 * @param {string} json JSON.stringify 的结果。
 * @returns {string} 可安全嵌入 application/json script 元素的文本。
 */
function escapeJsonForHtml(json) {
  return json
    .replace(/&/g, '\\u0026')
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}

function parseCliArguments(argv) {
  const result = { input: '', output: '' };
  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];
    if (argument === '--input' || argument === '--output') {
      const value = argv[index + 1];
      if (!value || value.startsWith('--')) {
        throw new Error(`${argument} 缺少路径参数`);
      }
      result[argument.slice(2)] = value;
      index += 1;
      continue;
    }
    throw new Error(`未知参数：${argument}`);
  }
  if (!result.input || !result.output) {
    throw new Error('用法：node generate-report.mjs --input analysis.json --output report.html');
  }
  return result;
}

function comparablePath(filePath) {
  const absolutePath = resolve(filePath);
  return process.platform === 'win32' ? absolutePath.toLowerCase() : absolutePath;
}

async function runCli() {
  const options = parseCliArguments(process.argv.slice(2));
  const inputPath = resolve(options.input);
  const outputPath = resolve(options.output);
  if (comparablePath(inputPath) === comparablePath(outputPath)) {
    throw new Error('输出路径不能与输入 JSON 路径相同');
  }

  const source = (await readFile(inputPath, 'utf8')).replace(/^\uFEFF/, '');
  let analysis;
  try {
    analysis = JSON.parse(source);
  } catch (error) {
    throw new Error(`无法解析输入 JSON：${error.message}`);
  }
  const writtenPath = await generateReport(analysis, outputPath);
  process.stdout.write(`报告已生成：${writtenPath}\n`);
}

const invokedPath = process.argv[1] ? comparablePath(process.argv[1]) : '';
if (invokedPath === comparablePath(SCRIPT_PATH)) {
  runCli().catch((error) => {
    process.stderr.write(`生成报告失败：${error.message}\n`);
    process.exitCode = 1;
  });
}
