// Generated by Skill uniapp-wechat-package-optimizer 1.0.0.
// 本文件仅使用 node:test 临时生成的合成报告数据，不包含真实业务数据、微信凭据或用户报告。
import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawn } from 'node:child_process';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

import { generateReport } from '../generate-report.mjs';

const GENERATOR_PATH = fileURLToPath(new URL('../generate-report.mjs', import.meta.url));

test('generateReport 生成离线单文件并安全转义嵌入 JSON', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'wechat-report-'));
  const outputPath = join(directory, 'nested', 'report.html');
  try {
    const writtenPath = await generateReport({
      schemaVersion: 1,
      project: { name: '</script><img src=x onerror=alert(1)> & \u2028 \u2029 $& $` $\'' },
      files: []
    }, outputPath);
    const html = await readFile(writtenPath, 'utf8');

    assert.equal(writtenPath, outputPath);
    assert.match(html, /<style>/);
    assert.match(html, /<script>/);
    assert.doesNotMatch(html, /<img src=x/);
    assert.match(html, /\\u003c\/script\\u003e\\u003cimg/);
    assert.match(html, /\\u0026/);
    assert.match(html, /\\u2028/);
    assert.match(html, /\\u2029/);
    const embedded = html.match(/<script id="report-data" type="application\/json">([\s\S]*?)<\/script>/);
    assert.ok(embedded);
    assert.equal(JSON.parse(embedded[1]).project.name, '</script><img src=x onerror=alert(1)> & \u2028 \u2029 $& $` $\'');
    assert.doesNotMatch(html, /__REPORT_DATA__/);
    assert.doesNotMatch(html, /https?:\/\/[^"']+\.(?:js|css)/i);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test('generateReport 可处理空值输入', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'wechat-report-empty-'));
  const outputPath = join(directory, 'report.html');
  try {
    await generateReport(null, outputPath);
    const html = await readFile(outputPath, 'utf8');
    assert.match(html, /<script id="report-data" type="application\/json">\{\}<\/script>/);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test('generateReport 拒绝覆写既有输出', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'wechat-report-existing-'));
  const outputPath = join(directory, 'report.html');
  try {
    await writeFile(outputPath, 'keep-me', 'utf8');
    await assert.rejects(generateReport({}, outputPath), { code: 'EEXIST' });
    assert.equal(await readFile(outputPath, 'utf8'), 'keep-me');
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test('CLI 拒绝覆写输入文件', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'wechat-report-cli-'));
  const inputPath = join(directory, 'analysis.json');
  try {
    await writeFile(inputPath, '{"schemaVersion":1}', 'utf8');
    const result = await runNode([GENERATOR_PATH, '--input', inputPath, '--output', inputPath]);
    assert.notEqual(result.code, 0);
    assert.match(result.stderr, /输出路径不能与输入 JSON 路径相同/);
    assert.equal(await readFile(inputPath, 'utf8'), '{"schemaVersion":1}');
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test('CLI 从任意工作目录生成报告', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'wechat-report-cli-success-'));
  const inputPath = join(directory, 'analysis.json');
  const outputPath = join(directory, 'output', 'report.html');
  try {
    await writeFile(inputPath, '\uFEFF' + JSON.stringify({ schemaVersion: 1, project: { name: 'CLI 样例' } }), 'utf8');
    const result = await runNode([GENERATOR_PATH, '--input', inputPath, '--output', outputPath], tmpdir());
    assert.equal(result.code, 0, result.stderr);
    assert.match(result.stdout, /报告已生成/);
    const html = await readFile(outputPath, 'utf8');
    assert.match(html, /"name":"CLI 样例"/);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

function runNode(argumentsList, workingDirectory) {
  return new Promise((resolvePromise, rejectPromise) => {
    const child = spawn(process.execPath, argumentsList, { cwd: workingDirectory, windowsHide: true });
    let stdout = '';
    let stderr = '';
    child.stdout.setEncoding('utf8');
    child.stderr.setEncoding('utf8');
    child.stdout.on('data', (chunk) => { stdout += chunk; });
    child.stderr.on('data', (chunk) => { stderr += chunk; });
    child.on('error', rejectPromise);
    child.on('close', (code) => { resolvePromise({ code, stdout, stderr }); });
  });
}
